name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
   contents: read
   id-token: write

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.12" ]

    steps:
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install --with dev

      - name: Run tests
        run: poetry run pytest --cov=src --cov-report html tests/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
             # Upload the coverage directory from the repository
             path: './htmlcov'


  #deploy:
  #  steps:
  #    - name: Build
  #      run: poetry build
  #    - name: Upload
  #      run: poetry publish

